norm_cruise_L_over_D: 7.558
norm_fast_L_over_D: 9.591
norm_root_cl_max: 1.381
norm_mass: 0.963
norm_payload_volume: 0.005727
norm_soaring_power: 33.84
norm_flight_angle: 7.537
norm_roll_stability: 0.126
