w_cruise_L_over_D: 1.0
w_fast_L_over_D: 0.7
w_root_cl_max: 0.2
w_mass: 1.0
w_safety_factor: 0.2
safety_factor_min: 13.0
w_static_margin: 0.2
static_margin_target:
- 0.02
- 0.15
w_cm0: 0.2
cm0_min: -0.02
w_payload_volume: 0.2
w_soaring_power: 0.7
w_flight_angle: 0.7
w_roll_stability: 0.3
invalid_penalty: 1000.0
constraint_penalty_scale: 1000.0
